# VLESS Reality: key material, inbound payload/creation and client link.

random_token() {
  len="${1:-16}"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 $((len * 2)) | tr -dc 'A-Za-z0-9' | head -c "$len"
  else
    date +%s | tr -dc 'A-Za-z0-9' | head -c "$len"
  fi
}

random_hex() {
  len="${1:-8}"
  if command -v openssl >/dev/null 2>&1; then
    bytes=$(((len + 1) / 2))
    openssl rand -hex "$bytes" | cut -c1-"$len"
  else
    date +%s | tr -dc 'a-f0-9' | head -c "$len"
  fi
}

vps_client_name() {
  printf "%s" "${VPS_HOST:-warren}" | tr -c 'A-Za-z0-9._-' '_' | sed 's/_$//'
}

generate_reality_materials() {
  panel_base_path="$(normalize_panel_base_path "${PANEL_BASE_PATH:-}")"
  panel_scheme="${PANEL_SCHEME:-https}"
  panel_curl_flags="${PANEL_CURL_FLAGS:-}"
  if [ -z "$panel_curl_flags" ]; then
    panel_curl_flags="--http1.1"
    [ "$panel_scheme" = "https" ] && panel_curl_flags="-k $panel_curl_flags"
  fi
  panel_api_base="${panel_scheme}://127.0.0.1:${PANEL_PORT}${panel_base_path}"
  panel_api_base="${panel_api_base%/}"
  cert_resp=""

  if command -v sing-box >/dev/null 2>&1; then
    cert_resp="$(sing-box generate reality-keypair 2>/dev/null || true)"
    if [ -n "$cert_resp" ]; then
      say "${GREEN}DONE${NC}  Reality keys generated by local sing-box"
    fi
  fi

  if [ -z "$cert_resp" ]; then
    xray_script_local="$(vps_workspace_dir)/panel-xray-x25519.sh"
    xray_script_remote="/tmp/warren-panel-xray-x25519.sh"

    {
      printf '#!/bin/sh\n'
      printf 'set -eu\n'
      printf 'if [ -x /usr/local/x-ui/bin/xray-linux-amd64 ]; then\n'
      printf '  /usr/local/x-ui/bin/xray-linux-amd64 x25519\n'
      printf 'elif command -v xray >/dev/null 2>&1; then\n'
      printf '  xray x25519\n'
      printf 'else\n'
      printf '  exit 1\n'
      printf 'fi\n'
    } > "$xray_script_local" || fail "Не удалось подготовить xray fallback script"
    chmod 700 "$xray_script_local" 2>/dev/null || true
    vps_write_remote_file "$xray_script_local" "$xray_script_remote" || fail "Не удалось загрузить xray helper на VPS"

    cert_resp="$(vps_ssh_timeout 20 "sh $(quote_sh "$xray_script_remote")" 2>/dev/null || true)"
    if [ -n "$cert_resp" ]; then
      say "${GREEN}DONE${NC}  Reality keys generated by local xray"
    fi
  fi

  if [ -z "${PANEL_API_TOKEN:-}" ]; then
    collect_3xui_api_token || true
  fi
  if [ -z "${PANEL_API_TOKEN:-}" ]; then
    say "${YELLOW}INFO${NC}  3x-ui API token still empty before Reality step"
  else
    say "${YELLOW}INFO${NC}  3x-ui API token loaded for Reality step"
  fi
  cert_cmd="curl ${panel_curl_flags} -fsSL --connect-timeout 5 --max-time 30"
  if [ -n "${PANEL_API_TOKEN:-}" ]; then
    cert_cmd="$cert_cmd -H \"Authorization: Bearer ${PANEL_API_TOKEN}\""
  fi
  cert_url="${panel_api_base}/panel/api/server/getNewX25519Cert"
  cert_cmd="$cert_cmd \"${cert_url}\""
  say "${YELLOW}INFO${NC}  Reality cert endpoint: $cert_url"

  if [ -z "$cert_resp" ]; then
    say "${YELLOW}INFO${NC}  Local xray did not return data, trying 3x-ui API"
  fi
  cert_attempt=0
  while [ -z "$cert_resp" ] && [ "$cert_attempt" -lt 5 ]; do
    say "${YELLOW}INFO${NC}  Reality cert attempt $((cert_attempt + 1))/5"
    cert_resp="$(vps_ssh_timeout 20 "sh -lc $(quote_sh "$cert_cmd")" 2>/dev/null || true)"
    if [ -n "$cert_resp" ]; then
      break
    fi
    cert_attempt=$((cert_attempt + 1))
    sleep 2
  done
  if [ -z "$cert_resp" ]; then
    say "${YELLOW}INFO${NC}  Reality API returned empty response"
  fi
  [ -n "$cert_resp" ] || fail "Не удалось сгенерировать X25519 ключи через API 3x-ui или локальный xray"

  cert_text="$(printf "%s\n" "$cert_resp" | tr -d '\r')"
  REALITY_PRIVATE_KEY="$(printf "%s" "$cert_text" | json_get_first_string "privateKey" "private_key" "privatekey" "privateKeyValue" 2>/dev/null || true)"
  REALITY_PUBLIC_KEY="$(printf "%s" "$cert_text" | json_get_first_string "publicKey" "public_key" "publickey" "publicKeyValue" "Password" "password" "Password (PublicKey)" 2>/dev/null || true)"
  if [ -z "$REALITY_PRIVATE_KEY" ] || [ -z "$REALITY_PUBLIC_KEY" ]; then
    REALITY_PRIVATE_KEY="$(printf "%s\n" "$cert_text" | sed -n 's/^PrivateKey: *//p' | head -n1 | tr -d ' \t\n\r')"
    [ -n "$REALITY_PUBLIC_KEY" ] || REALITY_PUBLIC_KEY="$(printf "%s\n" "$cert_text" | sed -n 's/^PublicKey: *//p' | head -n1 | tr -d ' \t\n\r')"
    [ -n "$REALITY_PUBLIC_KEY" ] || REALITY_PUBLIC_KEY="$(printf "%s\n" "$cert_text" | sed -n 's/^Password (PublicKey): *//p' | head -n1 | tr -d ' \t\n\r')"
  fi
  if [ -z "$REALITY_PRIVATE_KEY" ] || [ -z "$REALITY_PUBLIC_KEY" ]; then
    say "${YELLOW}INFO${NC}  Raw X25519 response: $cert_text"
  else
    say "${GREEN}DONE${NC}  Reality keys parsed successfully"
  fi
  [ -n "$REALITY_PRIVATE_KEY" ] || fail "Не удалось получить privateKey для Reality"
  [ -n "$REALITY_PUBLIC_KEY" ] || fail "Не удалось получить publicKey для Reality"

  CLIENT_UUID="$(cat /proc/sys/kernel/random/uuid 2>/dev/null || uuidgen 2>/dev/null || true)"
  [ -n "$CLIENT_UUID" ] || CLIENT_UUID="$(random_hex 8)-$(random_hex 4)-4$(random_hex 3)-a$(random_hex 3)-$(random_hex 12)"
  CLIENT_EMAIL="$(random_token 8)"
  CLIENT_SUBID="$(random_token 16)"
  CLIENT_COMMENT="$(vps_client_name)"

  SID_PRIMARY="$(random_hex 14)"
  SID_EXTRA_1="$(random_hex 16)"
  SID_EXTRA_2="$(random_hex 4)"
  SID_EXTRA_3="$(random_hex 8)"
  SID_EXTRA_4="$(random_hex 2)"
  SID_EXTRA_5="$(random_hex 10)"
  SID_EXTRA_6="$(random_hex 6)"
  SID_EXTRA_7="$(random_hex 12)"

  runtime_state_set "reality_private_key" "$REALITY_PRIVATE_KEY"
  runtime_state_set "reality_public_key" "$REALITY_PUBLIC_KEY"
  runtime_state_set "client_uuid" "$CLIENT_UUID"
  runtime_state_set "client_email" "$CLIENT_EMAIL"
  runtime_state_set "client_subid" "$CLIENT_SUBID"
  runtime_state_set "reality_sid" "$SID_PRIMARY"
}

create_vless_reality_payload() {
  INBOUND_REMARK="warren-reality"
  INBOUND_TAG="inbound-443"
  INBOUND_PORT="443"
  REALITY_TARGET="login.vk.com:443"
  REALITY_SERVER_NAME_1="login.vk.com"
  REALITY_SERVER_NAME_2="www.login.vk.com"
  REALITY_FINGERPRINT="chrome"
  REALITY_SPIDERX="/"
  CLIENT_FLOW="xtls-rprx-vision"

  inbound_json_local="$(vps_workspace_dir)/inbound-vless-reality.json"
  inbound_json_remote="/tmp/warren-inbound-vless-reality.json"

  cat > "$inbound_json_local" <<EOF
{
  "up": 0,
  "down": 0,
  "total": 0,
  "remark": "${INBOUND_REMARK}",
  "enable": true,
  "expiryTime": 0,
  "listen": "",
  "port": ${INBOUND_PORT},
  "protocol": "vless",
  "settings": "{\"clients\":[{\"comment\":\"${CLIENT_COMMENT}\",\"email\":\"${CLIENT_EMAIL}\",\"enable\":true,\"expiryTime\":0,\"flow\":\"${CLIENT_FLOW}\",\"id\":\"${CLIENT_UUID}\",\"limitIp\":0,\"reset\":0,\"subId\":\"${CLIENT_SUBID}\",\"tgId\":0,\"totalGB\":0}],\"decryption\":\"none\",\"encryption\":\"none\"}",
  "streamSettings": "{\"network\":\"tcp\",\"security\":\"reality\",\"externalProxy\":[],\"realitySettings\":{\"show\":false,\"xver\":0,\"target\":\"${REALITY_TARGET}\",\"serverNames\":[\"${REALITY_SERVER_NAME_1}\",\"${REALITY_SERVER_NAME_2}\"],\"privateKey\":\"${REALITY_PRIVATE_KEY}\",\"minClientVer\":\"\",\"maxClientVer\":\"\",\"maxTimediff\":0,\"shortIds\":[\"${SID_PRIMARY}\",\"${SID_EXTRA_1}\",\"${SID_EXTRA_2}\",\"${SID_EXTRA_3}\",\"${SID_EXTRA_4}\",\"${SID_EXTRA_5}\",\"${SID_EXTRA_6}\",\"${SID_EXTRA_7}\"],\"mldsa65Seed\":\"\",\"settings\":{\"publicKey\":\"${REALITY_PUBLIC_KEY}\",\"fingerprint\":\"${REALITY_FINGERPRINT}\",\"serverName\":\"\",\"spiderX\":\"${REALITY_SPIDERX}\",\"mldsa65Verify\":\"\"}},\"tcpSettings\":{\"acceptProxyProtocol\":false,\"header\":{\"type\":\"none\"}}}",
  "tag": "${INBOUND_TAG}",
  "sniffing": "{\"enabled\":false,\"destOverride\":[\"http\",\"tls\",\"quic\",\"fakedns\"],\"metadataOnly\":false,\"routeOnly\":false}"
}
EOF

  vps_write_remote_file "$inbound_json_local" "$inbound_json_remote" || fail "Не удалось загрузить inbound payload на VPS"
}

create_vless_reality_inbound() {
  panel_base_path="$(normalize_panel_base_path "${PANEL_BASE_PATH:-}")"
  panel_scheme="${PANEL_SCHEME:-https}"
  panel_curl_flags="${PANEL_CURL_FLAGS:-}"
  if [ -z "$panel_curl_flags" ]; then
    panel_curl_flags="--http1.1"
    [ "$panel_scheme" = "https" ] && panel_curl_flags="-k $panel_curl_flags"
  fi
  panel_api_base="${panel_scheme}://127.0.0.1:${PANEL_PORT}${panel_base_path}"
  panel_api_base="${panel_api_base%/}"
  inbound_api_script_local="$(vps_workspace_dir)/panel-inbound-api.sh"
  inbound_api_script_remote="/tmp/warren-panel-inbound-api.sh"

  # Build the inbound API script.
  # Auth preference: Bearer token (newer 3x-ui with api_tokens table) → session cookie fallback.
  _inbound_cookie="${PANEL_COOKIE_REMOTE:-/tmp/warren-panel.cookie}"
  {
    printf '#!/bin/sh\n'
    printf 'set -eu\n'
    printf 'panel_api_base=%s\n'      "$(quote_sh "$panel_api_base")"
    printf 'inbound_json_remote=%s\n' "$(quote_sh "$inbound_json_remote")"
    printf 'inbound_id=%s\n'          "$(quote_sh "${INBOUND_ID:-}")"
    printf 'cookie_file=%s\n'         "$(quote_sh "$_inbound_cookie")"
    printf 'curl_flags=%s\n'          "$(quote_sh "$panel_curl_flags")"
    printf 'token=%s\n'               "$(quote_sh "${PANEL_API_TOKEN:-}")"
    # v3.5 stores only a SHA256 digest in SQLite. Validate a candidate bearer
    # with a safe GET before choosing it; otherwise use the authenticated
    # browser session and its CSRF token.
    printf 'if [ -n "$token" ]; then\n'
    printf '  auth_code="$(curl $curl_flags -sS -o /dev/null -w "%%{http_code}" --connect-timeout 5 --max-time 20 -H "Authorization: Bearer $token" "$panel_api_base/panel/api/server/status" 2>/dev/null || true)"\n'
    printf '  [ "$auth_code" = "200" ] || token=""\n'
    printf 'fi\n'
    printf 'if [ -n "$token" ]; then\n'
    # Delete existing inbound (if any) then add new one — Bearer auth
    printf '  if [ -n "$inbound_id" ]; then\n'
    printf '    curl $curl_flags -fsSL --connect-timeout 5 --max-time 30 -H "Authorization: Bearer $token" -X POST "$panel_api_base/panel/api/inbounds/del/$inbound_id" >/dev/null 2>&1 || true\n'
    printf '  fi\n'
    printf '  curl $curl_flags -fsSL --connect-timeout 5 --max-time 30 -H "Authorization: Bearer $token" -H "Content-Type: application/json" -X POST --data @"$inbound_json_remote" "$panel_api_base/panel/api/inbounds/add"\n'
    printf 'elif [ -f "$cookie_file" ]; then\n'
    # Session mutations require X-CSRF-Token in modern 3x-ui.
    printf '  csrf_resp="$(curl $curl_flags -fsSL --connect-timeout 5 --max-time 20 -b "$cookie_file" -c "$cookie_file" "$panel_api_base/csrf-token")"\n'
    printf '  csrf_token="$(printf "%%s" "$csrf_resp" | sed -n '\''s/.*"obj"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p'\'' | head -n1)"\n'
    printf '  [ -n "$csrf_token" ] || { echo "missing 3x-ui CSRF token" >&2; exit 1; }\n'
    printf '  if [ -n "$inbound_id" ]; then\n'
    printf '    curl $curl_flags -fsSL --connect-timeout 5 --max-time 30 -b "$cookie_file" -c "$cookie_file" -H "X-CSRF-Token: $csrf_token" -X POST "$panel_api_base/panel/api/inbounds/del/$inbound_id" >/dev/null 2>&1 || true\n'
    printf '  fi\n'
    printf '  curl $curl_flags -fsSL --connect-timeout 5 --max-time 30 -b "$cookie_file" -c "$cookie_file" -H "X-CSRF-Token: $csrf_token" -H "Content-Type: application/json" -X POST --data @"$inbound_json_remote" "$panel_api_base/panel/api/inbounds/add"\n'
    printf 'else\n'
    printf '  echo "missing 3x-ui api token and no session cookie" >&2; exit 1\n'
    printf 'fi\n'
  } > "$inbound_api_script_local" || fail "Не удалось подготовить inbound API script"
  chmod 700 "$inbound_api_script_local" 2>/dev/null || true
  vps_write_remote_file "$inbound_api_script_local" "$inbound_api_script_remote" || fail "Не удалось загрузить inbound API script на VPS"
  say "${YELLOW}INFO${NC}  3x-ui inbound add endpoint: ${panel_api_base}/panel/api/inbounds/add"

  add_resp="$(vps_ssh_timeout 60 "sh $(quote_sh "$inbound_api_script_remote")")" \
    || fail "Не удалось создать VLESS + Reality inbound через API 3x-ui"

  printf "%s" "$add_resp" | json_has_success_true || fail "API 3x-ui не подтвердил создание inbound"
  INBOUND_ID="$(printf "%s" "$add_resp" | json_get_number "id")"
  runtime_state_set "inbound_id" "$INBOUND_ID"
}

build_vless_link() {
  VLESS_LINK="vless://${CLIENT_UUID}@${VPS_HOST}:${INBOUND_PORT}?type=tcp&security=reality&pbk=${REALITY_PUBLIC_KEY}&fp=${REALITY_FINGERPRINT}&sni=${REALITY_SERVER_NAME_1}&sid=${SID_PRIMARY}&spx=%2F&flow=${CLIENT_FLOW}#${CLIENT_COMMENT}"
  runtime_state_set "vless_link" "$VLESS_LINK"
}

configure_vless_reality() {
  if ! login_3xui_api; then
    warn "Не удалось войти в web API 3x-ui; продолжаю через root-доступ и API token из SQLite"
    collect_3xui_api_token || fail "Не удалось получить API token 3x-ui из SQLite"
  fi
  generate_reality_materials
  create_vless_reality_payload
  create_vless_reality_inbound
  build_vless_link

  REPORT_FILE="$(vps_report_file)"
  runtime_state_set "vps_report_file" "$REPORT_FILE"

  {
    printf "Warren VPS setup report\n"
    printf "=======================\n\n"
    printf "VLESS inbound link: %s\n\n" "${VLESS_LINK:-unknown}"
    printf "Host: %s\n" "$VPS_HOST"
    printf "SSH port: %s\n" "$VPS_SSH_PORT"
    printf "SSH root login: %s\n" "root"
    printf "SSH root password: %s\n" "${VPS_ROOT_PASSWORD:-unknown}"
    printf "Password storage note: root password was kept during setup and removed from warren.conf after success; this 0600 report remains the recovery copy.\n"
    printf "OS: %s\n" "${VPS_OS_PRETTY:-unknown}"
    printf "3x-ui URL: %s\n" "${PANEL_URL:-unknown}"
    printf "3x-ui username: %s\n" "${PANEL_USERNAME:-unknown}"
    printf "3x-ui password: %s\n" "${PANEL_PASSWORD:-unknown}"
    printf "\nReality public key: %s\n" "${REALITY_PUBLIC_KEY:-unknown}"
    printf "Reality short id: %s\n" "${SID_PRIMARY:-unknown}"
    printf "Client email: %s\n" "${CLIENT_EMAIL:-unknown}"
    printf "Client uuid: %s\n" "${CLIENT_UUID:-unknown}"
    printf "Reality config status: %s\n" "created"
  } > "$REPORT_FILE" || fail "Не удалось записать локальный отчёт по VPS"
  chmod 600 "$REPORT_FILE" 2>/dev/null || true

  save_remote_artifact
  vps_step_done "VLESS + Reality inbound создан, локальный отчёт записан: $REPORT_FILE"
}
