#!/bin/sh
# Regenerate or verify docs/SYMBOLS.md: every shell function grouped by file.
# Functions inside heredoc payloads (generated router/VPS scripts) are listed
# separately, because they run in another process and share names like log().

set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OUT="$PROJECT_DIR/docs/SYMBOLS.md"
CHECK_ONLY=0
[ "${1:-}" != "--check" ] || CHECK_ONLY=1

TMP_OUT="${TMPDIR:-/tmp}/warren-symbols.$$"
trap 'rm -f "$TMP_OUT"' EXIT HUP INT TERM

list_file() {
  rel="$1"
  awk -v rel="$rel" '
    function flush_payload() {
      if (payload_names != "") {
        printf "- payload `%s`: %s\n", tag, payload_names
      }
      payload_names = ""
    }
    tag == "" && /<<-?[[:space:]]*["\047]?[A-Z_][A-Z0-9_]*["\047]?/ {
      match($0, /<<-?[[:space:]]*["\047]?[A-Z_][A-Z0-9_]*/)
      tag = substr($0, RSTART, RLENGTH)
      gsub(/[<\-"\047[:space:]]/, "", tag)
      next
    }
    tag != "" {
      line = $0
      sub(/^[[:space:]]+/, "", line)
      if (line == tag) { flush_payload(); tag = ""; next }
      if (match($0, /^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*\(\)/)) {
        name = substr($0, RSTART, RLENGTH); gsub(/[[:space:]()]/, "", name)
        payload_names = payload_names (payload_names == "" ? "" : ", ") "`" name "`"
      }
      next
    }
    /^[A-Za-z_][A-Za-z0-9_]*\(\)/ {
      name = $0; sub(/\(\).*/, "", name)
      names = names (names == "" ? "" : ", ") "`" name "`"
    }
    END {
      if (names != "") printf "- %s\n", names
    }
  ' "$PROJECT_DIR/$rel"
}

{
  printf "# Warren symbol index\n\n"
  printf "Generated by \`sh tools/gen-index.sh\`; do not edit by hand. \`tools/check.sh\` fails when it is stale.\n"
  printf "Architecture map: [INDEX.md](INDEX.md).\n"
  for rel in warren.sh bootstrap.sh $(cd "$PROJECT_DIR" && ls lib/*.sh tools/*.sh tools/remote-admin/*.sh tests/*.sh); do
    printf "\n## %s\n\n" "$rel"
    body="$(list_file "$rel")"
    if [ -n "$body" ]; then printf "%s\n" "$body"; else printf "_no functions_\n"; fi
  done
} > "$TMP_OUT"

if [ "$CHECK_ONLY" = "1" ]; then
  if ! cmp -s "$TMP_OUT" "$OUT"; then
    printf "%s\n" "docs/SYMBOLS.md is stale; run: sh tools/gen-index.sh" >&2
    exit 1
  fi
  exit 0
fi

mkdir -p "$(dirname "$OUT")"
mv "$TMP_OUT" "$OUT"
printf "%s\n" "Updated $OUT"
